services:
  # Servidor Web de Next.js (El cuartel general del ataque)
  app:
    container_name: stress-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@stress-db:5432/stress_db?schema=public
      - NODE_ENV=production
    depends_on:
      stress-db:
        condition: service_healthy
    networks:
      - stress-net  # 👈 Conectado a la red

  # Base de Datos PostgreSQL
  stress-db:
    container_name: stress-db
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stress_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stress_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - stress-net  # 👈 Conectado a la red

  # Administrador Visual de la Base de Datos (pgAdmin)
  stress-pgadmin:
    container_name: stress-pgadmin
    image: dpage/pgadmin4:8.5
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - stress-db
    networks:
      - stress-net  # 👈 Conectado a la red

  # Laboratorio de Analítica de Datos (Jupyter Notebook)
  jupyter_lab:
    container_name: stress-ai-lab
    image: jupyter/scipy-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=stresslab
    networks:
      - stress-net  # 👈 Conectado a la red

volumes:
  pgdata:

# 🖧 LA NUEVA SECCIÓN QUE UNE TODO:
networks:
  stress-net:
    driver: bridge
